# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Covertable < Formula
  desc "Generate coverage table by files"
  homepage "https://github.com/gilcu2/covertable"
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/gilcu2/covertable/releases/download/v0.2.1/covertable_Darwin_x86_64.tar.gz"
      sha256 "7643f71cff2a5319e869db45ea3f05ccde3f60d55489a6aa442dad429f670580"

      def install
        bin.install "covertable"
      end
    end
    on_arm do
      url "https://github.com/gilcu2/covertable/releases/download/v0.2.1/covertable_Darwin_arm64.tar.gz"
      sha256 "f5d0af32f6f682b7968dc704a6e78c89917c130207b06971527fdea267d166a5"

      def install
        bin.install "covertable"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gilcu2/covertable/releases/download/v0.2.1/covertable_Linux_x86_64.tar.gz"
        sha256 "30c37650bf4264b3705dc390694bb1ecf09a8616a71ba421bd3be1305e58ecd5"

        def install
          bin.install "covertable"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gilcu2/covertable/releases/download/v0.2.1/covertable_Linux_arm64.tar.gz"
        sha256 "476793fb2500a3c7af22b8507a469546d7477f3b0b753140974ddaac031e8a42"

        def install
          bin.install "covertable"
        end
      end
    end
  end
end
