# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topdiffxml < Formula
  desc "Generate top differences between 2 xml documents."
  homepage "https://github.com/gilcu2/topdiffxml"
  version "0.3.4"
  depends_on :macos

  on_intel do
    url "https://github.com/gilcu2/topdiffxml/releases/download/0.3.4/topdiffxml_Darwin_x86_64.tar.gz"
    sha256 "1b2b9e65a7dd2dc743ab8d0e78b802178e0d5f68531fd9a188d04055f6facd56"

    def install
      bin.install "topdiffxml"
    end
  end
  on_arm do
    url "https://github.com/gilcu2/topdiffxml/releases/download/0.3.4/topdiffxml_Darwin_arm64.tar.gz"
    sha256 "01a77c5f7924e5509b5a6b0ab6a5b4b1e4e42214d953003c5d851d57683db20b"

    def install
      bin.install "topdiffxml"
    end
  end
end
