# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topdiffxml < Formula
  desc "Generate top differences between 2 xml documents."
  homepage "https://github.com/gilcu2/topdiffxml"
  version "0.4.2"
  depends_on :macos

  on_intel do
    url "https://github.com/gilcu2/topdiffxml/releases/download/v0.4.2/topdiffxml_Darwin_x86_64.tar.gz"
    sha256 "f6b6f11b1504dcfea35466b78635e474340ad9c607d14f42bcb29a8f2256cb43"

    def install
      bin.install "topdiffxml"
    end
  end
  on_arm do
    url "https://github.com/gilcu2/topdiffxml/releases/download/v0.4.2/topdiffxml_Darwin_arm64.tar.gz"
    sha256 "871e25d9e182851373a14232584cf3b15a7e768540e5aa068dfbb884466c1237"

    def install
      bin.install "topdiffxml"
    end
  end
end
